# Generated by Django 3.0.4 on 2020-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
